before_script:
  - npm install

stages:
  - build
  - test
  - accessibility

build_job:
  stage: build
  script: echo "Building the app"

test_job:
  stage: test
  script: echo "Testing the app"

a11y_check:
  stage: accessibility
  script: npm-run-all serve-public pa11y-ci:sitemap kill-server
