module.exports = {
  'abhishek.thakur@sprinklr.com': {
    name: 'Abhishek Thakur',
    email: 'abhishek.thakur@sprinklr.com',
    avatar: 'https://secure.gravatar.com/avatar/891cdb5f7d0e2752894880d7ebf481fe?s=64&d=identicon',
    gitlabUrl: 'https://prod-gitlab.sprinklr.com/abhishek.thakur',
    _avatar_fetch_url: 'https://prod-gitlab.sprinklr.com/api/v4/avatar?email=abhishek.thakur@sprinklr.com&size=32',
  },
  'akhurana@sprinklr.com': {
    name: 'Abhishek Khurana',
    email: 'akhurana@sprinklr.com',
    avatar: 'https://secure.gravatar.com/avatar/364452db3aa17af06858c8aeabaac78a?s=64&d=identicon',
    gitlabUrl: 'https://prod-gitlab.sprinklr.com/akhurana',
    _avatar_fetch_url: 'https://prod-gitlab.sprinklr.com/api/v4/avatar?email=akhurana@sprinklr.com&size=32',
  },
  'aneree.mehta@sprinklr.com': {
    name: 'Aneree Mehta',
    email: 'aneree.mehta@sprinklr.com',
    avatar: 'https://secure.gravatar.com/avatar/c097c3d2145c935d4aab55679d1da417?s=64&d=identicon',
    gitlabUrl: 'https://prod-gitlab.sprinklr.com/aneree.mehta',
    _avatar_fetch_url: 'https://prod-gitlab.sprinklr.com/api/v4/avatar?email=aneree.mehta@sprinklr.com&size=32',
  },
  'akash.modi@sprinklr.com': {
    name: 'Akash Modi',
    email: 'akash.modi@sprinklr.com',
    avatar: 'https://secure.gravatar.com/avatar/6daf08bbb852e1c836d4fbab7cb7bd15?s=64\u0026d=identicon',
    gitlabUrl: 'https://prod-gitlab.sprinklr.com/akash.modi',
    _avatar_fetch_url: 'https://prod-gitlab.sprinklr.com/api/v4/avatar?email=akash.modi@sprinklr.com&size=32',
  },
  'ashish.kumar@sprinklr.com': {
    name: 'Ashish Kumar',
    email: 'ashish.kumar@sprinklr.com',
    avatar: 'https://secure.gravatar.com/avatar/34bd1c022e04b2bdfa620d445eae1250?s=64\u0026d=identicon',
    gitlabUrl: 'https://prod-gitlab.sprinklr.com/ashish.kumar',
    _avatar_fetch_url: 'https://prod-gitlab.sprinklr.com/api/v4/avatar?email=ashish.kumar@sprinklr.com&size=32',
  },
  'aviral.varshney@sprinklr.com': {
    name: 'Aviral Varshney',
    email: 'aviral.varshney@sprinklr.com',
    avatar: 'https://secure.gravatar.com/avatar/808433a15216c28a6de800e7db6492d4?s=64\u0026d=identicon',
    gitlabUrl: 'https://prod-gitlab.sprinklr.com/aviral.varshney',
    _avatar_fetch_url: 'https://prod-gitlab.sprinklr.com/api/v4/avatar?email=aviral.varshney@sprinklr.com&size=32',
  },
  'chinmay.chaudhary@sprinklr.com': {
    name: 'Chinmay Chaudhary',
    email: 'chinmay.chaudhary@sprinklr.com',
    avatar: 'https://secure.gravatar.com/avatar/e26e80645aa48123b453a42c31bca18a?s=64&d=identicon',
    gitlabUrl: 'https://prod-gitlab.sprinklr.com/chinmay.chaudhary',
    _avatar_fetch_url: 'https://prod-gitlab.sprinklr.com/api/v4/avatar?email=chinmay.chaudhary@sprinklr.com&size=32',
  },
  'dhruvil.sutariya@sprinklr.com': {
    name: 'dhruvil.sutariya',
    email: 'dhruvil.sutariya@sprinklr.com',
    avatar: 'https://secure.gravatar.com/avatar/17bef42224cc3298ca32d1c4158e3ef0?s=64\u0026d=identicon',
    gitlabUrl: 'https://prod-gitlab.sprinklr.com/dhruvil.sutariya',
    _avatar_fetch_url: 'https://prod-gitlab.sprinklr.com/api/v4/avatar?email=dhruvil.sutariya@sprinklr.com&size=32',
  },
  'hardik.modi@sprinklr.com': {
    name: 'Hardik Modi',
    email: 'hardik.modi@sprinklr.com',
    avatar: 'https://secure.gravatar.com/avatar/f4dd4f4c060ffd3ea66775d20f43451d?s=64\u0026d=identicon',
    gitlabUrl: 'https://prod-gitlab.sprinklr.com/hardik.modi',
    _avatar_fetch_url: 'https://prod-gitlab.sprinklr.com/api/v4/avatar?email=hardik.modi@sprinklr.com&size=32',
  },
  'harsh.vyas@sprinklr.com': {
    name: 'Harsh Vyas',
    email: 'harsh.vyas@sprinklr.com',
    avatar: 'https://secure.gravatar.com/avatar/bf2571fa205fd4a1ee1714b84450aab0?s=64&d=identicon',
    gitlabUrl: 'https://prod-gitlab.sprinklr.com/harsh.vyas',
    _avatar_fetch_url: 'https://prod-gitlab.sprinklr.com/api/v4/avatar?email=harsh.vyas@sprinklr.com&size=32',
  },

  'ivan.torres@sprinklr.com': {
    name: 'Ivan Torres',
    email: 'ivan.torres@sprinklr.com',
    avatar: 'https://secure.gravatar.com/avatar/ea8539532f6df53f357164e48aa408de?s=64&d=identicon',
    gitlabUrl: 'https://prod-gitlab.sprinklr.com/ivan.torres',
    _avatar_fetch_url: 'https://prod-gitlab.sprinklr.com/api/v4/avatar?email=ivan.torres@sprinklr.com&size=32',
  },
  'joel.turner@sprinklr.com': {
    name: 'Joel Turner',
    email: 'joel.turner@sprinklr.com',
    avatar: 'https://secure.gravatar.com/avatar/b6820c4806c11f557e62445e00af6546?s=64&d=identicon',
    gitlabUrl: 'https://prod-gitlab.sprinklr.com/joel.turner',
    _avatar_fetch_url: 'https://prod-gitlab.sprinklr.com/api/v4/avatar?email=joel.turner@sprinklr.com&size=32',
  },
  'kevin.vegda@sprinklr.com': {
    name: 'Kevin Vegda',
    email: 'kevin.vegda@sprinklr.com',
    avatar: 'https://secure.gravatar.com/avatar/f68196bd2b4ea316358f2a97d5875e64?s=64&d=identicon',
    gitlabUrl: 'https://prod-gitlab.sprinklr.com/kevin.vegda',
    _avatar_fetch_url: 'https://prod-gitlab.sprinklr.com/api/v4/avatar?email=kevin.vegda@sprinklr.com&size=32',
  },
  'mihir.shah@sprinklr.com': {
    name: 'mihir.shah',
    email: 'mihir.shah@sprinklr.com',
    avatar: 'https://secure.gravatar.com/avatar/847f13c7afbf7e4a119811852ba0f362?s=64&d=identicon',
    gitlabUrl: 'https://prod-gitlab.sprinklr.com/mihir.shah',
    _avatar_fetch_url: 'https://prod-gitlab.sprinklr.com/api/v4/avatar?email=mihir.shah@sprinklr.com&size=32',
  },
  'parth.shah@sprinklr.com': {
    name: 'Parth',
    email: 'parth.shah@sprinklr.com',
    avatar: 'https://secure.gravatar.com/avatar/6d833933f8af441ebd0c3e91cede8f74?s=64&d=identicon',
    gitlabUrl: 'https://prod-gitlab.sprinklr.com/parth.shah',
    _avatar_fetch_url: 'https://prod-gitlab.sprinklr.com/api/v4/avatar?email=parth.shah@sprinklr.com&size=32',
  },
  'patel.maulik@sprinklr.com': {
    name: 'Maulik Patel',
    email: 'patel.maulik@sprinklr.com',
    avatar: 'https://secure.gravatar.com/avatar/5ffb3ff75a893e3a84ddf4f6c71f786e?s=64&d=identicon',
    gitlabUrl: 'https://prod-gitlab.sprinklr.com/patel.maulik',
    _avatar_fetch_url: 'https://prod-gitlab.sprinklr.com/api/v4/avatar?email=patel.maulik@sprinklr.com&size=32',
  },
  'ryan.legler@sprinklr.com': {
    name: 'Ryan Legler',
    email: 'ryan.legler@sprinklr.com',
    avatar: 'https://secure.gravatar.com/avatar/013cee4bf15de8c56b671ed41e31de12?s=64&d=identicon',
    gitlabUrl: 'https://prod-gitlab.sprinklr.com/ryan.legler',
    _avatar_fetch_url: 'https://prod-gitlab.sprinklr.com/api/v4/avatar?email=ryan.legler@sprinklr.com&size=32',
  },
  'saagar.takhi@sprinklr.com': {
    name: 'Saagar Takhi',
    email: 'saagar.takhi@sprinklr.com',
    avatar: 'https://secure.gravatar.com/avatar/a977886a624615c322e5f71a2b03ee54?s=64&d=identicon',
    gitlabUrl: 'https://prod-gitlab.sprinklr.com/saagar.takhi',
    _avatar_fetch_url: 'https://prod-gitlab.sprinklr.com/api/v4/avatar?email=saagar.takhi@sprinklr.com&size=32',
  },
  'sahil.jain@sprinklr.com': {
    name: 'sahiljain',
    email: 'sahil.jain@sprinklr.com',
    avatar: 'https://secure.gravatar.com/avatar/a86691b5c38c889a61b323a43f6c3564?s=64&d=identicon',
    gitlabUrl: 'https://prod-gitlab.sprinklr.com/sahil.jain',
    _avatar_fetch_url: 'https://prod-gitlab.sprinklr.com/api/v4/avatar?email=sahil.jain@sprinklr.com&size=32',
  },
  'shriya.juneja@sprinklr.com': {
    name: 'Shriya Juneja',
    email: 'shriya.juneja@sprinklr.com',
    avatar: 'https://secure.gravatar.com/avatar/55869bec75c45d24353c5c89ec97e041?s=64\u0026d=identicon',
    gitlabUrl: 'https://prod-gitlab.sprinklr.com/shriya.juneja',
    _avatar_fetch_url: 'https://prod-gitlab.sprinklr.com/api/v4/avatar?email=shriya.juneja@sprinklr.com&size=32',
  },

  'stanley.johnson@sprinklr.com': {
    name: 'Stanley Johnson',
    email: 'stanley.johnson@sprinklr.com',
    avatar: 'https://secure.gravatar.com/avatar/e87fcd5b5e46f0a26a4b3dfda3c240b0?s=64&d=identicon',
    gitlabUrl: 'https://prod-gitlab.sprinklr.com/stanley.johnson',
    _avatar_fetch_url: 'https://prod-gitlab.sprinklr.com/api/v4/avatar?email=stanley.johnson@sprinklr.com&size=32',
  },
  'ujjawal.pabreja@sprinklr.com': {
    name: 'Ujjawal Pabreja',
    email: 'ujjawal.pabreja@sprinklr.com',
    avatar: 'https://secure.gravatar.com/avatar/337ab1c18bfacbf67f74d815768db15d?s=64\u0026d=identicon',
    gitlabUrl: 'https://prod-gitlab.sprinklr.com/ujjawal.pabreja',
    _avatar_fetch_url: 'https://prod-gitlab.sprinklr.com/api/v4/avatar?email=ujjawal.pabreja@sprinklr.com&size=32',
  },
  'ysoni@sprinklr.com': {
    name: 'Yash Soni',
    email: 'ysoni@sprinklr.com',
    avatar: 'https://secure.gravatar.com/avatar/35ce2a72cb49d8c681c27b092599a900?s=64&d=identicon',
    gitlabUrl: 'https://prod-gitlab.sprinklr.com/ysoni',
    _avatar_fetch_url: 'https://prod-gitlab.sprinklr.com/api/v4/avatar?email=ysoni@sprinklr.com&size=32',
  },
};
