import type { Event, Intent } from '@sprinklr/spaceweb-calendar';
import addMinutes from 'date-fns/addMinutes';

const INTENTS: Intent[] = ['error', 'success', 'warning'];
export const getRandomIntent = () => {
  function randomInteger(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
  }
  return INTENTS[randomInteger(0, 2)];
};

const currentDate = new Date();
export const EVENTS: Event[] = [
  {
    id: 0,
    end: addMinutes(currentDate, 3658),
    start: addMinutes(currentDate, 3403),
    intent: 'success',
    title: 'Event 0',
  },
  {
    id: 1,
    start: addMinutes(currentDate, -3523),
    end: addMinutes(currentDate, -3283),
    intent: 'warning',
    title: 'Event 1',
  },
  {
    id: 2,
    end: addMinutes(currentDate, 2188),
    start: addMinutes(currentDate, 1918),
    intent: 'error',
    title: 'Event 2',
  },
  {
    id: 3,
    start: addMinutes(currentDate, -2023),
    end: addMinutes(currentDate, -1783),
    intent: 'warning',
    title: 'Event 3',
  },
  {
    id: 4,
    end: addMinutes(currentDate, 5113),
    start: addMinutes(currentDate, 4918),
    intent: 'success',
    title: 'Event 4',
  },
  {
    id: 5,
    end: addMinutes(currentDate, 5023),
    start: addMinutes(currentDate, 4648),
    intent: 'warning',
    title: 'Event 5',
  },
  {
    id: 6,
    end: addMinutes(currentDate, 2308),
    start: addMinutes(currentDate, 1483),
    intent: 'success',
    title: 'Event 6',
  },
  {
    id: 7,
    end: addMinutes(currentDate, 8038),
    start: addMinutes(currentDate, 7768),
    intent: 'warning',
    title: 'Event 7',
  },
  {
    id: 8,
    start: addMinutes(currentDate, -7753),
    end: addMinutes(currentDate, -7498),
    intent: 'success',
    title: 'Event 8',
  },
  {
    id: 9,
    start: addMinutes(currentDate, -7453),
    end: addMinutes(currentDate, -7378),
    intent: 'warning',
    title: 'Event 9',
  },
  {
    id: 10,
    end: addMinutes(currentDate, 6193),
    start: addMinutes(currentDate, 6163),
    intent: 'warning',
    title: 'Event 10',
  },
  {
    id: 11,
    start: addMinutes(currentDate, -4573),
    end: addMinutes(currentDate, -4558),
    intent: 'error',
    title: 'Event 11',
  },
  {
    id: 12,
    start: addMinutes(currentDate, -733),
    end: addMinutes(currentDate, -643),
    intent: 'warning',
    title: 'Event 12',
  },
  {
    id: 13,
    end: addMinutes(currentDate, 3748),
    start: addMinutes(currentDate, 3073),
    intent: 'success',
    title: 'Event 13',
  },
  {
    id: 14,
    end: addMinutes(currentDate, 6073),
    start: addMinutes(currentDate, 5998),
    intent: 'error',
    title: 'Event 14',
  },
  {
    id: 15,
    end: addMinutes(currentDate, 571),
    start: addMinutes(currentDate, 991),
    intent: 'success',
    title: 'Event 15',
  },
  {
    id: 16,
    end: addMinutes(currentDate, 1111),
    start: addMinutes(currentDate, 1291),
    intent: 'warning',
    title: 'Event 16',
  },
  {
    id: 17,
    start: addMinutes(currentDate, -2041),
    end: addMinutes(currentDate, -2401),
    intent: 'warning',
    title: 'Event 17',
  },
  {
    id: 18,
    start: addMinutes(currentDate, -3631),
    end: addMinutes(currentDate, -3811),
    intent: 'error',
    title: 'Event 18',
  },
  {
    id: 19,
    end: addMinutes(currentDate, 4906),
    start: addMinutes(currentDate, 5701),
    intent: 'error',
    title: 'Event 19',
  },
  {
    id: 20,
    start: addMinutes(currentDate, -5191),
    end: addMinutes(currentDate, -5476),
    intent: 'error',
    title: 'Event 20',
  },
  {
    id: 21,
    start: addMinutes(currentDate, -3916),
    end: addMinutes(currentDate, -3931),
    intent: 'warning',
    title: 'Event 21',
  },
  {
    id: 22,
    end: addMinutes(currentDate, 6466),
    start: addMinutes(currentDate, 6646),
    intent: 'error',
    title: 'Event 22',
  },
  {
    id: 23,
    start: addMinutes(currentDate, -6376),
    end: addMinutes(currentDate, -6436),
    intent: 'error',
    title: 'Event 23',
  },
  {
    id: 24,
    end: addMinutes(currentDate, 7906),
    start: addMinutes(currentDate, 8116),
    intent: 'error',
    title: 'Event 24',
  },
  {
    id: 25,
    start: addMinutes(currentDate, -2401),
    end: addMinutes(currentDate, -2431),
    intent: 'error',
    title: 'Event 25',
  },
  {
    id: 26,
    start: addMinutes(currentDate, -2551),
    end: addMinutes(currentDate, -2701),
    intent: 'success',
    title: 'Event 26',
  },
  {
    id: 27,
    start: addMinutes(currentDate, -2191),
    end: addMinutes(currentDate, -2521),
    intent: 'warning',
    title: 'Event 27',
  },
  {
    id: 28,
    end: addMinutes(currentDate, 9391),
    start: addMinutes(currentDate, 9511),
    intent: 'warning',
    title: 'Event 28',
  },
  {
    id: 29,
    start: addMinutes(currentDate, -10936),
    end: addMinutes(currentDate, -11041),
    intent: 'error',
    title: 'Event 29',
  },
  {
    id: 30,
    start: addMinutes(currentDate, -6721),
    end: addMinutes(currentDate, -6841),
    intent: 'error',
    title: 'Event 30',
  },
  {
    id: 31,
    start: addMinutes(currentDate, -10651),
    end: addMinutes(currentDate, -10936),
    intent: 'error',
    title: 'Event 31',
  },
  {
    id: 32,
    end: addMinutes(currentDate, 6541),
    start: addMinutes(currentDate, 6556),
    intent: 'warning',
    title: 'Event 32',
  },
  {
    id: 33,
    end: addMinutes(currentDate, 8161),
    start: addMinutes(currentDate, 8326),
    intent: 'success',
    title: 'Event 33',
  },
];
