import spaceCommon from './common';

module.exports = {
  name: 'space-light',
  htmlFontSize: '10px',
  theme: {
    ...spaceCommon,
    app: {
      header: '#0A0A14',
      headerTab: 'rgba(255, 255, 255, 0.1)',
      headerTabHover: 'rgba(255, 255, 255, 0.2)',
      headerTabActive: '#FFFFFF',
      headerText: 'rgba(255, 255, 255, 0.6)',
      headerTextHover: '#FFFFFF',
    },
    cht: {
      bg: '#F3EAE1',
      border: '#E6D4CA',
      bubbleLeft: '#FFFFFF',
      bubbleRight: '#EBEBFF',
      bubbleSupportingText: '#646470',
      bubbleTextLeft: '#0A0A14',
      bubbleTextRight: '#0A0A14',
      bubbleBorder: '#C7D3F7',
      bubbleIcon1: '#646470',
      bubbleIcon2: '#D7D7DC',
      bubbleIcon3: '#0828CC',
      bubbleInsert: '#F8F8FA',
      bubbleLink: '#0828CC',
      bubbleText: '#646470',
      reply: '#FFFFFF',
      footer: '#F3EAE1',
      hover: 'rgba(100, 100, 112, 0.07)',
      read: '#006CD7',
      unread: '#A0A0A8',
    },
    __tokens: {
      spr: {
        'ui-01': { value: '#FFFFFF', cssProperty: 'backgroundColor' },
        'ui-02': { value: '#F8F8FA', cssProperty: 'backgroundColor' },
        'ui-03': { value: '#F2F2F4', cssProperty: 'backgroundColor' },
        'ui-04': { value: '#0828CC', cssProperty: 'backgroundColor' },
        'ui-05': { value: '#F2F2F4', cssProperty: 'backgroundColor' },
        'ui-06': { value: '#E6E6E9', cssProperty: 'backgroundColor' },
        'ui-focus': { value: 'rgba(8, 40, 204, 0.07)', cssProperty: 'backgroundColor' },
        'ui-focus-reverse': { value: 'rgba(255, 255, 255, 0.2)', cssProperty: 'backgroundColor' },
        'ui-hover': { value: 'rgba(8, 40, 204, 0.05)', cssProperty: 'backgroundColor' },
        'ui-hover-reverse': { value: 'rgba(255, 255, 255, 0.1)', cssProperty: 'backgroundColor' },
        'support-error': { value: '#E44045', cssProperty: 'backgroundColor' },
        'support-error-highlight': { value: 'rgba(255, 96, 96, 0.1)', cssProperty: 'backgroundColor' },
        'support-success': { value: '#3fbf41', cssProperty: 'backgroundColor' },
        'support-success-highlight': { value: 'rgba(63, 191, 65, 0.07)', cssProperty: 'backgroundColor' },
        'support-warning': { value: '#EEC202', cssProperty: 'backgroundColor' },
        'support-warning-highlight': { value: 'rgba(238, 194, 2, 0.1)', cssProperty: 'backgroundColor' },
        'clr-blue-highlight': { value: '#E8F0FE', cssProperty: 'backgroundColor' },
        tag: { value: '#F2F2F4', cssProperty: 'backgroundColor' },
        'tag-01': { value: '#F2F2F4', cssProperty: 'backgroundColor' },
        'tag-02': { value: 'rgba(8, 40, 204, 0.07)', cssProperty: 'backgroundColor' },
        field: { value: '#DBDBDB', cssProperty: 'backgroundColor' },
        popup: { value: '#FFFFFF', cssProperty: 'backgroundColor' },
        overlay: { value: 'rgba(10, 10, 20, 0.9)', cssProperty: 'backgroundColor' },
        'tooltip-01': { value: '#0A0A14', cssProperty: 'backgroundColor' },
        highlight: { value: 'rgba(255, 231, 173, 0.7)', cssProperty: 'backgroundColor' },
        favourite: { value: '#FF9F21', cssProperty: 'backgroundColor' },
        notification: { value: '#C6202B', cssProperty: 'backgroundColor' },
        'interactive-01': { value: '#0828CC', cssProperty: 'backgroundColor' },
        'interactive-hover': { value: '#0729a0', cssProperty: 'backgroundColor' },
        'interactive-disable': { value: 'rgba(255, 255, 255, 0.8)', cssProperty: 'backgroundColor' },
        'interactive-02': { value: '#646470', cssProperty: 'backgroundColor' },
        'clr-blue': { value: '#0AA2FF', cssProperty: 'backgroundColor' },
        'clr-green': { value: '#20963a', cssProperty: 'backgroundColor' },
        'clr-lavender': { value: '#7F36F6', cssProperty: 'backgroundColor' },
        'clr-orange': { value: '#F08C1A', cssProperty: 'backgroundColor' },
        'clr-pink': { value: '#DE456B', cssProperty: 'backgroundColor' },
        'clr-red': { value: '#E44045', cssProperty: 'backgroundColor' },
        'clr-sea': { value: '#16AAD2', cssProperty: 'backgroundColor' },
        'clr-teal': { value: '#13C18D', cssProperty: 'backgroundColor' },
        'clr-yellow': { value: '#DEAC09', cssProperty: 'backgroundColor' },
        'clr-grey': { value: '#D7D7DC', cssProperty: 'backgroundColor' },
        'clr-purple': { value: '#8C43FF', cssProperty: 'backgroundColor' },
        'clr-lt-yellow': { value: '#FFD04F', cssProperty: 'backgroundColor' },
        'clr-darker-blue': { value: '#327AFD', cssProperty: 'backgroundColor' },
        'secondary-yellow': { value: '#FFC312', cssProperty: 'backgroundColor' },
        'secondary-green': { value: '#A3CB38', cssProperty: 'backgroundColor' },
        'secondary-teal': { value: '#12CBC4', cssProperty: 'backgroundColor' },
        'secondary-lt-pink': { value: '#FDA7DF', cssProperty: 'backgroundColor' },
        'secondary-pink': { value: '#ED4C67', cssProperty: 'backgroundColor' },
        'secondary-maroon': { value: '#B53471', cssProperty: 'backgroundColor' },
        'secondary-orange': { value: '#F48749', cssProperty: 'backgroundColor' },
        hover: { value: '#0828CC', cssProperty: 'borderColor' },
        'focus-01': { value: '#0828CC', cssProperty: 'borderColor' },
        'border-01': { value: '#F2F2F4', cssProperty: 'borderColor' },
        'border-02': { value: '#ECECEF', cssProperty: 'borderColor' },
        'border-03': { value: '#D7D7DC', cssProperty: 'borderColor' },
        'border-04': { value: '#A0A0A8', cssProperty: 'borderColor' },
        'border-05': { value: '#FFFFFF', cssProperty: 'borderColor' },
        'border-06': { value: '#0A0A14', cssProperty: 'borderColor' },
        'card-border': { value: '#ECECEF', cssProperty: 'borderColor' },
        'popup-border': { value: '#D7D7DC', cssProperty: 'borderColor' },
        'tooltip-border': { value: '#0A0A14', cssProperty: 'borderColor' },
        'interactive-focus': { value: '#132a86', cssProperty: 'borderColor' },
        'shadow-01': { value: '0 1px 4px 0 rgba(10,10,20,0.15)', cssProperty: 'boxShadow' },
        'shadow-02': { value: '0 2px 8px 0 rgba(10,10,20,0.20)', cssProperty: 'boxShadow' },
        'shadow-03': { value: '-2px 9px 12px 0 rgba(10,10,20,0.60)', cssProperty: 'boxShadow' },
        'shadow-04': { value: '0px -2px 8px 0px rgba(10,10,20,0.2)', cssProperty: 'boxShadow' },
        'shadow-05': { value: '0px 3px 4px 0 rgba(0,0,0,0.1)', cssProperty: 'boxShadow' },
        'shadow-06': { value: '0px -3px 4px 0 rgba(0,0,0,0.1)', cssProperty: 'boxShadow' },
        'icon-01': { value: '#0A0A14', cssProperty: 'fill' },
        'icon-02': { value: '#646470', cssProperty: 'fill' },
        'icon-03': { value: '#646470', cssProperty: 'fill' },
        'icon-04': { value: '#0828CC', cssProperty: 'fill' },
        'icon-05': { value: '#FFFFFF', cssProperty: 'fill' },
        'icon-06': { value: 'rgba(255, 255, 255, 0.6)', cssProperty: 'fill' },
        'icon-hover': { value: '#0A0A14', cssProperty: 'fill' },
        'icon-disable': { value: '#D7D7DC', cssProperty: 'fill' },
        'icon-hover-reverse': { value: '#FFFFFF', cssProperty: 'fill' },
        'icon-error': { value: '#FF6060', cssProperty: 'fill' },
        link: { value: '#0828CC', cssProperty: 'color' },
        'text-01': { value: '#0A0A14', cssProperty: 'color' },
        'text-02': { value: '#434350', cssProperty: 'color' },
        'text-03': { value: '#646470', cssProperty: 'color' },
        'text-04': { value: '#0828CC', cssProperty: 'color' },
        'text-05': { value: '#FFFFFF', cssProperty: 'color' },
        'text-06': { value: '#FFFFFF', cssProperty: 'color' },
        'text-placeholder': { value: '#646470', cssProperty: 'color' },
        'support-error-text': { value: '#C6202B', cssProperty: 'color' },
        'support-success-text': { value: '#20963a', cssProperty: 'color' },
        'support-warning-text': { value: '#DEAC09', cssProperty: 'color' },
      },
      nav: {
        'ui-01': { value: 'rgba(255, 255, 255, 0.2)', cssProperty: 'backgroundColor' },
        'ui-hover-01': { value: 'rgba(255, 255, 255, 0.3)', cssProperty: 'backgroundColor' },
        'icon-01': { value: 'rgba(255, 255, 255, 0.9)', cssProperty: 'fill' },
        'icon-focus-01': { value: '#327AFD', cssProperty: 'fill' },
        'text-01': { value: 'rgba(255, 255, 255, 0.9)', cssProperty: 'color' },
      },
    },
    outline: {
      '01': { color: '#0828CC', width: '2px', offset: '2px', style: 'solid' },
    },
  },
};
