// SPACEWEB-GENERATED-REACT-ICON
// DO NOT EDIT THIS FILE DIRECTLY, SEE README.md
import * as React from 'react';
import { useStyle } from '../../style';
import Icon from '../icon';
import { IconProps } from '../types';

export default function Alert(props: IconProps): React.ReactElement {
  const { theme, isRTL } = useStyle();
  return (
    <Icon viewBox="0 0 12 12" data-icon-name="Alert" {...props}>
      <path d="M5.904 6.5a.5.5 0 0 1-.5-.5V3.25a.5.5 0 1 1 1 0V6a.5.5 0 0 1-.5.5z" />
      <circle cx="5.904" cy="8.161" r=".589" />
      <path d="M6 12c-3.308 0-6-2.69-6-6s2.692-6 6-6 6 2.692 6 6-2.691 6-6 6zM6 1C3.244 1 1 3.243 1 6s2.244 5 5 5 5-2.243 5-5-2.243-5-5-5z" />
    </Icon>
  );
}
