// SPACEWEB-GENERATED-REACT-ICON
// DO NOT EDIT THIS FILE DIRECTLY, SEE README.md
import * as React from 'react';
import { useStyle } from '../../style';
import Icon from '../icon';
import { IconProps } from '../types';

export default function CalendarSolid(props: IconProps): React.ReactElement {
  const { theme, isRTL } = useStyle();
  return (
    <Icon viewBox="0 0 15 15" data-icon-name="CalendarSolid" {...props}>
      <path d="M12.4 1.6c.9 0 1.7.8 1.7 1.7v1.2H0V3.3c0-.9.8-1.7 1.7-1.7h.9V0h1.6v1.6h5.6V0h1.6v1.6h1zM0 13.4V6.1h14.1v7.3c0 .9-.8 1.6-1.7 1.6H1.7C.8 15 0 14.3 0 13.4z" />
    </Icon>
  );
}
