// SPACEWEB-GENERATED-REACT-ICON
// DO NOT EDIT THIS FILE DIRECTLY, SEE README.md
import * as React from 'react';
import { useStyle } from '../../style';
import Icon from '../icon';
import { IconProps } from '../types';

export default function ChevronLeft(props: IconProps): React.ReactElement {
  const { theme, isRTL } = useStyle();
  return (
    <Icon
      viewBox="0 0 14 14"
      data-icon-name="ChevronLeft"
      {...props}
      className={isRTL ? [{ transform: 'scaleX(-1)' }, props.className] : props.className}
    >
      <path d="M10.693 13.728a.931.931 0 00-.001-1.316L5.282 7l5.41-5.41A.93.93 0 009.379.271h-.001l-6.07 6.07a.931.931 0 000 1.316l6.069 6.07a.931.931 0 001.316 0z" />
    </Icon>
  );
}
