// SPACEWEB-GENERATED-REACT-ICON
// DO NOT EDIT THIS FILE DIRECTLY, SEE README.md
import * as React from 'react';
import { useStyle } from '../../style';
import Icon from '../icon';
import { IconProps } from '../types';

export default function ChevronRight(props: IconProps): React.ReactElement {
  const { theme, isRTL } = useStyle();
  return (
    <Icon
      viewBox="0 0 14 14"
      data-icon-name="ChevronRight"
      {...props}
      className={isRTL ? [{ transform: 'scaleX(-1)' }, props.className] : props.className}
    >
      <path d="M3.307.272a.931.931 0 00.001 1.316L8.718 7l-5.41 5.41a.93.93 0 001.313 1.318h.001l6.07-6.07a.931.931 0 000-1.316L4.623.272a.931.931 0 00-1.316 0z" />
    </Icon>
  );
}
