// SPACEWEB-GENERATED-REACT-ICON
// DO NOT EDIT THIS FILE DIRECTLY, SEE README.md
import * as React from 'react';
import { useStyle } from '../../style';
import Icon from '../icon';
import { IconProps } from '../types';

export default function ImagePreview(props: IconProps): React.ReactElement {
  const { theme, isRTL } = useStyle();
  return (
    <Icon viewBox="0 0 14 14" data-icon-name="ImagePreview" {...props}>
      <circle fillRule="evenodd" clipRule="evenodd" cx="12.5" cy="3.35" r="1.5" />
      <path d="M9.33 14H0l3.87-5.5c.36-.52 1.29-.51 1.64 0L9.33 14zm1.52-.01l-1.52-2.18 1.2-1.4c.09-.13.25-.22.3-.19.11 0 .22.06.3.17L14 14h-3.15v-.01z" />
    </Icon>
  );
}
