// SPACEWEB-GENERATED-REACT-ICON
// DO NOT EDIT THIS FILE DIRECTLY, SEE README.md
import * as React from 'react';
import { useStyle } from '../../style';
import Icon from '../icon';
import { IconProps } from '../types';

export default function Search(props: IconProps): React.ReactElement {
  const { theme, isRTL } = useStyle();
  return (
    <Icon viewBox="0 0 12 12" data-icon-name="Search" {...props}>
      <path d="M11.854 11.149L7.75 7.037a4.32 4.32 0 00.946-2.68A4.356 4.356 0 004.348 0a4.357 4.357 0 000 8.713 4.299 4.299 0 002.7-.969l4.102 4.11a.496.496 0 00.704 0 .5.5 0 000-.705zM4.348 7.716a3.36 3.36 0 010-6.719 3.36 3.36 0 010 6.719z" />
    </Icon>
  );
}
