import hyperspaceCommon from './common';

module.exports = {
  name: 'hyperspace-light',
  htmlFontSize: '10px',
  theme: {
    ...hyperspaceCommon,
    app: {
      header: '#0A0A14',
      headerTab: 'rgba(255, 255, 255, 0.1)',
      headerTabHover: 'rgba(255, 255, 255, 0.2)',
      headerTabActive: '#EEEEEE',
      headerText: 'rgba(255, 255, 255, 0.6)',
      headerTextHover: '#FFFFFF',
    },
    cht: {
      bg: '#F3EAE1',
      border: '#E6D4CA',
      bubbleLeft: '#FFFFFF',
      bubbleRight: '#EBEBFF',
      bubbleSupportingText: '#646470',
      bubbleTextLeft: '#0A0A14',
      bubbleTextRight: '#0A0A14',
      bubbleBorder: '#C7D3F7',
      bubbleIcon1: '#646470',
      bubbleIcon2: '#D7D7DC',
      bubbleIcon3: '#0828CC',
      bubbleInsert: '#F8F8FA',
      bubbleLink: '#0828CC',
      bubbleText: '#646470',
      reply: '#FFFFFF',
      footer: '#F3EAE1',
      hover: 'rgba(100, 100, 112, 0.07)',
      read: '#006CD7',
      unread: '#A0A0A8',
    },
    __tokens: {
      spr: {
        'ui-01': { value: '#FFFFFF', cssProperty: 'backgroundColor' },
        'ui-02': { value: '#F8F8FA', cssProperty: 'backgroundColor' },
        'ui-03': { value: '#DBDBDB', cssProperty: 'backgroundColor' },
        'ui-04': { value: '#0E61F6', cssProperty: 'backgroundColor' },
        'ui-05': { value: '#EEF0F1', cssProperty: 'backgroundColor' },
        'ui-06': { value: '#E6E6E9', cssProperty: 'backgroundColor' },
        'ui-focus': {
          value: 'rgba(8, 40, 204, 0.07)',
          cssProperty: 'backgroundColor',
        },
        'ui-focus-reverse': {
          value: 'rgba(255, 255, 255, 0.2)',
          cssProperty: 'backgroundColor',
        },
        'ui-hover': { value: '#F8F8FA', cssProperty: 'backgroundColor' },
        'ui-hover-reverse': {
          value: 'rgba(255, 255, 255, 0.1)',
          cssProperty: 'backgroundColor',
        },
        'support-error': { value: '#C70F5C', cssProperty: 'backgroundColor' },
        'support-error-highlight': {
          value: 'rgba(199, 15, 92, 0.2)',
          cssProperty: 'backgroundColor',
        },
        'support-success': { value: '#6AC96E', cssProperty: 'backgroundColor' },
        'support-success-highlight': {
          value: 'rgba(106, 201, 110, 0.2)',
          cssProperty: 'backgroundColor',
        },
        'support-warning': { value: '#F3BF24', cssProperty: 'backgroundColor' },
        'support-warning-highlight': {
          value: 'rgba(243, 191, 36, 0.2)',
          cssProperty: 'backgroundColor',
        },
        'clr-blue-highlight': { value: '#E8F0FE', cssProperty: 'backgroundColor' },
        tag: { value: '#F2F2F4', cssProperty: 'backgroundColor' },
        'tag-01': { value: '#E6E6E9', cssProperty: 'backgroundColor' },
        'tag-02': {
          value: 'rgba(8, 40, 204, 0.07)',
          cssProperty: 'backgroundColor',
        },
        field: { value: '#DBDBDB', cssProperty: 'backgroundColor' },
        popup: { value: '#FFFFFF', cssProperty: 'backgroundColor' },
        overlay: {
          value: 'rgba(10, 10, 20, 0.9)',
          cssProperty: 'backgroundColor',
        },
        'tooltip-01': { value: '#0A0A14', cssProperty: 'backgroundColor' },
        highlight: {
          value: 'rgba(255, 231, 173, 0.7)',
          cssProperty: 'backgroundColor',
        },
        favourite: { value: '#FF9F21', cssProperty: 'backgroundColor' },
        notification: { value: '#DE336A', cssProperty: 'backgroundColor' },
        'interactive-01': { value: '#0E61F6', cssProperty: 'backgroundColor' },
        'interactive-hover': { value: '#1858CE', cssProperty: 'backgroundColor' },
        'interactive-disable': {
          value: 'rgba(255, 255, 255, 0.6)',
          cssProperty: 'backgroundColor',
        },
        'interactive-02': { value: '#DBDBDB', cssProperty: 'backgroundColor' },
        'clr-blue': { value: '#2EA2FB', cssProperty: 'backgroundColor' },
        'clr-green': { value: '#33CC99', cssProperty: 'backgroundColor' },
        'clr-lavender': { value: '#7F36F6', cssProperty: 'backgroundColor' },
        'clr-orange': { value: '#F08C1A', cssProperty: 'backgroundColor' },
        'clr-pink': { value: '#FFA1BE', cssProperty: 'backgroundColor' },
        'clr-red': { value: '#E1245E', cssProperty: 'backgroundColor' },
        'clr-sea': { value: '#16AAD2', cssProperty: 'backgroundColor' },
        'clr-teal': { value: '#13C18D', cssProperty: 'backgroundColor' },
        'clr-yellow': { value: '#ECAD00', cssProperty: 'backgroundColor' },
        'clr-grey': { value: '#D7D7DC', cssProperty: 'backgroundColor' },
        'interactive-focus': { value: '#132a86', cssProperty: 'borderColor' },
        'clr-purple': { value: '#8C43FF', cssProperty: 'backgroundColor' },
        'clr-lt-yellow': { value: '#FFD04F', cssProperty: 'backgroundColor' },
        'clr-darker-blue': { value: '#327AFD', cssProperty: 'backgroundColor' },
        'secondary-yellow': { value: '#FFC312', cssProperty: 'backgroundColor' },
        'secondary-green': { value: '#A3CB38', cssProperty: 'backgroundColor' },
        'secondary-teal': { value: '#12CBC4', cssProperty: 'backgroundColor' },
        'secondary-lt-pink': { value: '#FDA7DF', cssProperty: 'backgroundColor' },
        'secondary-pink': { value: '#ED4C67', cssProperty: 'backgroundColor' },
        'secondary-maroon': { value: '#B53471', cssProperty: 'backgroundColor' },
        'secondary-orange': { value: '#F48749', cssProperty: 'backgroundColor' },
        'icon-01': { value: '#0A0A14', cssProperty: 'fill' },
        'icon-02': { value: '#646470', cssProperty: 'fill' },
        'icon-03': { value: '#818192', cssProperty: 'fill' },
        'icon-04': { value: '#0E61F6', cssProperty: 'fill' },
        'icon-05': { value: '#FFFFFF', cssProperty: 'fill' },
        'icon-06': { value: 'rgba(255, 255, 255, 0.6)', cssProperty: 'fill' },
        'icon-hover': { value: '#0A0A14', cssProperty: 'fill' },
        'icon-disable': { value: '#DBDBDB', cssProperty: 'fill' },
        'icon-hover-reverse': { value: '#FFFFFF', cssProperty: 'fill' },
        'icon-error': { value: '#C70F5C', cssProperty: 'fill' },
        link: { value: '#0E61F6', cssProperty: 'color' },
        'text-01': { value: '#0A0A14', cssProperty: 'color' },
        'text-02': { value: '#434350', cssProperty: 'color' },
        'text-03': { value: '#646470', cssProperty: 'color' },
        'text-04': { value: '#0E61F6', cssProperty: 'color' },
        'text-05': { value: '#FFFFFF', cssProperty: 'color' },
        'text-06': { value: '#FFFFFF', cssProperty: 'color' },
        'text-placeholder': { value: '#646470', cssProperty: 'color' },
        'support-error-text': { value: '#C70F5C', cssProperty: 'color' },
        'support-success-text': { value: '#6AC96E', cssProperty: 'color' },
        'support-warning-text': { value: '#F3BF24', cssProperty: 'color' },
        hover: { value: '#0729a0', cssProperty: 'borderColor' },
        'focus-01': { value: '#0E61F6', cssProperty: 'borderColor' },
        'border-01': { value: '#EEEEEE', cssProperty: 'borderColor' },
        'border-02': { value: '#E6E6E9', cssProperty: 'borderColor' },
        'border-03': { value: '#DBDBDB', cssProperty: 'borderColor' },
        'border-04': { value: '#818192', cssProperty: 'borderColor' },
        'border-05': { value: '#FFFFFF', cssProperty: 'borderColor' },
        'border-06': { value: '#0A0A14', cssProperty: 'borderColor' },
        'card-border': { value: '#ECECEF', cssProperty: 'borderColor' },
        'popup-border': { value: '#D7D7DC', cssProperty: 'borderColor' },
        'tooltip-border': { value: '#0A0A14', cssProperty: 'borderColor' },
        'focus-02': { value: '1px solid #0E61F6', cssProperty: 'outline' },
        'shadow-01': {
          value: '0 1px 4px 0 rgba(10,10,20,0.15)',
          cssProperty: 'boxShadow',
        },
        'shadow-02': {
          value: '0 2px 8px 0 rgba(10,10,20,0.20)',
          cssProperty: 'boxShadow',
        },
        'shadow-03': {
          value: '-2px 9px 12px 0 rgba(10,10,20,0.60)',
          cssProperty: 'boxShadow',
        },
        'shadow-04': {
          value: '-2px 5px 12px -4px rgba(10,10,20,.20)',
          cssProperty: 'boxShadow',
        },
        'shadow-05': {
          value: '0px 3px 4px 0 rgba(0,0,0,0.1)',
          cssProperty: 'boxShadow',
        },
        'shadow-06': {
          value: '0px -3px 4px 0 rgba(0,0,0,0.1)',
          cssProperty: 'boxShadow',
        },
      },
      nav: {
        'ui-01': {
          value: 'rgba(255, 255, 255, 0.2)',
          cssProperty: 'backgroundColor',
        },
        'ui-hover-01': {
          value: 'rgba(255, 255, 255, 0.3)',
          cssProperty: 'backgroundColor',
        },
        'icon-01': {
          value: 'rgba(255, 255, 255, 0.9)',
          cssProperty: 'fill',
        },
        'icon-focus-01': {
          value: '#0E61F6',
          cssProperty: 'fill',
        },
        'text-01': {
          value: 'rgba(255, 255, 255, 0.9)',
          cssProperty: 'color',
        },
      },
    },
    outline: {
      '01': { color: '#0E61F6', width: '2px', offset: '2px', style: 'solid' },
    },
  },
};
